
quarkus.rest-client.obras-api.url=https://api.artic.edu/api/v1
%test.quarkus.rest-client.obras-api.url=http://localhost:${quarkus.wiremock.devservices.port}

quarkus.rest-client.logging.scope=REQUEST_RESPONSE
quarkus.rest-client.logging.body-limit=1000

